name: "sesame"

services:
  sesame-app-manager:
    container_name: sesame-app-manager
    image: ghcr.io/libertech-fr/sesame-app-manager:latest
    restart: always
    depends_on:
      - sesame-orchestrator
    environment:
      - SESAME_APP_API_URL=<public_url_orchestrator>
    volumes:
      - ./configs/sesame-app-manager/statics:/data/src/public/config
    ports:
      - "3000"
    networks:
      - sesame
      - reverse
    labels:
      - "traefik.enable=true"
      #Décommenter la ligne suivante pour rediriger en HTTPS
#      - "traefik.http.routers.sesame-app-manager.tls=true"
      - "traefik.http.routers.sesame-app-manager.rule=Host(`<public_url_app_manager>`)"
      - "traefik.http.services.sesame-app-manager.loadbalancer.server.port=3000"
      
  sesame-orchestrator:
    container_name: sesame-orchestrator
    image: ghcr.io/libertech-fr/sesame-orchestrator:latest
    restart: always
    depends_on:
      - sesame-mongo
      - sesame-redis
    environment:
      - SESAME_REDIS_URI=redis://sesame-redis:6379
      - SESAME_MONGO_URI=mongodb://sesame-mongo:27017/sesame
      - SESAME_JWT_SECRET=<your_jwt_secret>
    volumes:
      - ./configs/sesame-orchestrator/jsonforms:/data/configs/identities/jsonforms
      - ./configs/sesame-orchestrator/validations:/data/configs/identities/validations
    ports:
      - "4000"
    networks:
      - sesame
      - reverse
    labels:
      - "traefik.enable=true"
      #Décommenter la ligne suivante pour rediriger en HTTPS
#     - "traefik.http.routers.sesame-orchestrator.tls=true"
      - "traefik.http.routers.sesame-orchestrator.rule=Host(`<public_url_orchestrator>`)"
      - "traefik.http.services.sesame-orchestrator.loadbalancer.server.port=4000"

  sesame-daemon:
    container_name: sesame-daemon
    image: ghcr.io/libertech-fr/sesame-daemon:latest
    restart: always
    depends_on:
      - sesame-redis
    environment:
      - SESAME_REDIS_URI=redis://sesame-redis:6379
    networks:
      - sesame
    volumes:
      - ./configs/sesame-daemon/backends:/data/backends

  sesame-mongo:
    image: mongo:7.0
    container_name: sesame-mongo
    command: --replSet rs0 --wiredTigerCacheSizeGB 1.5
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
    restart: always
    networks:
      - sesame
    volumes:
      - sesame-mongo:/data/db

  sesame-redis:
    image: redis
    container_name: sesame-redis
    volumes:
      - sesame-redis:/data
    restart: always
    networks:
      - sesame
    command: redis-server --appendonly yes

volumes:
  sesame-mongo:
  sesame-redis:

networks:
  sesame:
  reverse:
    external: true
