name: reverse

services:
  traefik:
    container_name: traefik
    restart: always
    image: "traefik:${TRAEFIK_DOCKER_VERSION:-v2.8}"
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - "${TRAEFIK_DOCKER_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/data:/etc/traefik
      - ./traefik/providers:/providers
      - ./traefik/log:/var/log/traefik
      - ./traefik/passwd:/passwd
#    environment:
#      - "OVH_ENDPOINT=${TRAEFIK_PROVIDER_OVH_ENDPOINT:-ovh-eu}"
#      - "OVH_APPLICATION_KEY=${TRAEFIK_PROVIDER_OVH_ENDPOINT:?application key required}"
#      - "OVH_APPLICATION_SECRET=${TRAEFIK_PROVIDER_OVH_ENDPOINT:?application secret required}"
#      - "OVH_CONSUMER_KEY=${TRAEFIK_PROVIDER_OVH_ENDPOINT:?consumer key required}"
    networks:
      - reverse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catchall_router.entrypoints=http"
      - "traefik.http.routers.catchall_router.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.catchall_router.priority=1"
#      - "traefik.http.routers.catchall_router.middlewares=SecuredChain@file"
#      - "traefik.http.routers.catchall_router_ssl.entrypoints=https"
#      - "traefik.http.routers.catchall_router_ssl.middlewares=SecuredChain@file"
#      - "traefik.http.routers.catchall_router_ssl.tls=true"
#      - "traefik.http.routers.catchall_router_ssl.tls.certresolver=ovh"
#      - "traefik.http.services.catchall_service.loadbalancer.server.port=80"
#      - "traefik.http.routers.catchall_router_ssl.rule=HostRegexp(`{any:.*}`)"
#      - "traefik.http.routers.catchall_router_ssl.priority=1"

#      - "traefik.http.routers.catchall_router_ssl.tls.domains[0].main=${TRAEFIK_TLS_DOMAINS_0:?tls domains 0 required}"
#      - "traefik.http.routers.catchall_router_ssl.tls.domains[0].sans=*.${TRAEFIK_TLS_DOMAINS_0:?tls domains 0 required}"

networks:
  reverse:
    external: true