type: Group
label: Identité
elements:
- type: HorizontalLayout
  elements:
  - type: Control
    label: UID
    scope: "#/properties/uid"
    options:
      required: true
  - type: Control
    label: CN
    scope: "#/properties/cn"
    options:
      required: true
      readOnly: true
  - type: Control
    label: Nom
    scope: "#/properties/sn"
    options:
      readOnly: true
      required: true
- type: HorizontalLayout
  elements:
  - type: Control
    label: Nom d'affichage
    scope: "#/properties/displayName"
    options:
      readOnly: true
  - type: Control
    label: Prénom
    scope: "#/properties/givenName"
    options:
      readOnly: true
- type: HorizontalLayout
  elements:
  - type: Control
    label: Email
    scope: "#/properties/mail"
    options:
      format: email
  - type: Control
    label: Mobile
    scope: "#/properties/mobile"
    options:
      readOnly: true
  - type: Control
    label: Adresse postale
    scope: "#/properties/postalAddress"
    options:
      readOnly: true
- type: HorizontalLayout
  elements:
  - type: Control
    label: language préféré
    scope: "#/properties/preferredLanguage"
    options:
      required: false
      suggestion:
        - FR
        - EN
        - DE
        - IT
  - type: Control
    label: Téléphone
    scope: "#/properties/telephoneNumber"
    options:
      readOnly: true
  - type: Control
    label: Titre
    scope: "#/properties/title"
