services:
  sesame-gestion-mdp:
    container_name: sesame-gestion-mdp
    image: ghcr.io/libertech-fr/sesame-gestion-mdp:latest
    restart: always
    env_file: .env
    ports: 
      - 3002:3000
    volumes:
      - "./config:/data/src/public"
    networks:
      - sesame 

networks:
  sesame:
    external: true
