services:
  sesame-app-manager:
    container_name: sesame-gestion-mdp
    image: ghcr.io/libertech-fr/sesame-gestion-mdp:latest
    restart: always
    ports: 
      - 3002:3000
    network:
      - sesame 

networks:
  sesame:
    external: true
